
services:
  streamlit_app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY} # Replace with your actual Gemini API Key
    command: streamlit run app.py --server.port 8501 --server.enableCORS false --server.enableXsrfProtection false
